name: Lints
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: Golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.46.2
  editorconfig:
    name: EditorConfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ECLint
        uses: snow-actions/eclint@v1.0.1
        with:
          args: check

