name: Testing

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  build:
    name: Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.16'
          - '1.17'
    steps:

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test -v -count=1 -race ./...
      env:
        FORCE_COLOR: true
